name: Build Docker Image

on: workflow_call

jobs:

  build_jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests

      - name: Extract JAR
        run: java -Djarmode=layertools -jar target/*.jar extract --destination docker-build/extracted-jar

      - name: Create deps list
        run: jdeps --ignore-missing-deps -q --recursive --multi-release 21 --print-module-deps --class-path 'docker-build/extracted-jar/dependencies/BOOT-INF/lib/*' target/*.jar > docker-build/jdk-modules.info

      - name: Move Dockerfile
        run: mv Dockerfile ./docker-build/

      - name: Remove snapshot deps path
        run: rm -rf docker-build/extracted-jar/snapshot-dependencies

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: docker_build_path
          path: ./docker-build
          retention-days: 1

  build_docker_img:
    runs-on: ubuntu-latest
    needs: [ build_jar ]

    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4.1.4
        with:
          name: docker_build_path

      - name: DockerHub Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build Docker image
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/employee-service

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/employee-service